In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import OneHotEncoder


pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [2]:
addi = pd.read_excel('../data/raw_data/2021 County Health Rankings Data - v1mmerge.xlsx', sheet_name='Additional Measure Data' )#, 'Ranked Measure Data'])

In [3]:
ran = pd.read_excel('../data/raw_data/2021 County Health Rankings Data - v1mmerge.xlsx', sheet_name='Ranked Measure Data' )#, 'Ranked Measure Data'])

In [4]:
ran.head()

,FIPS,State,County,% Smokers,% Adults with Obesity,% Physically Inactive,% Excessive Drinking,% Severe Housing Problems
0,1001,Alabama,Autauga,19.810766,33.0,30.6,14.473886,13.630967
1,1003,Alabama,Baldwin,18.513318,30.0,24.7,18.736958,12.996651
2,1005,Alabama,Barbour,25.530768,41.2,28.0,12.466974,13.710555
3,1007,Alabama,Bibb,23.084813,37.4,33.4,15.420603,9.255242
4,1009,Alabama,Blount,22.954959,33.0,33.3,15.833284,10.125665

In [5]:
addi.head()

,FIPS,State,County,Population,% Adults with Diabetes,% Food Insecure,% Limited Access to Healthy Foods,% Uninsured,% Less Than 18 Years of Age,% 65 and Over,% Rural
0,1001,Alabama,Autauga,55869,12.7,15.6,11.991125,13.007961,23.206071,15.973080,42.002162
1,1003,Alabama,Baldwin,223234,10.3,12.9,5.424427,16.753438,21.302311,20.977987,42.279099
2,1005,Alabama,Barbour,24686,17.5,21.9,10.739667,17.673231,20.586567,19.691323,67.789635
3,1007,Alabama,Bibb,22394,13.6,15.1,2.601627,13.429904,20.349201,16.669644,68.352607
4,1009,Alabama,Blount,57826,14.6,13.6,2.880150,17.934702,22.922215,18.700930,89.951502

In [6]:
addi[addi['County'].isin(ran['County']) == False].head()

Empty DataFrame
Columns: [FIPS, State, County, Population, % Adults with Diabetes, % Food Insecure, % Limited Access to Healthy Foods, % Uninsured, % Less Than 18 Years of Age, % 65 and Over, % Rural]
Index: []

In [7]:
ran[ran['County'].isin(addi['County']) == False].head()

Empty DataFrame
Columns: [FIPS, State, County, % Smokers, % Adults with Obesity, % Physically Inactive, % Excessive Drinking, % Severe Housing Problems]
Index: []

In [8]:
health = pd.merge(ran, addi, how='inner', on=['State', 'County'])

In [9]:
health.head()

,FIPS_x,State,County,% Smokers,% Adults with Obesity,% Physically Inactive,% Excessive Drinking,% Severe Housing Problems,FIPS_y,Population,% Adults with Diabetes,% Food Insecure,% Limited Access to Healthy Foods,% Uninsured,% Less Than 18 Years of Age,% 65 and Over,% Rural
0,1001,Alabama,Autauga,19.810766,33.0,30.6,14.473886,13.630967,1001,55869,12.7,15.6,11.991125,13.007961,23.206071,15.973080,42.002162
1,1003,Alabama,Baldwin,18.513318,30.0,24.7,18.736958,12.996651,1003,223234,10.3,12.9,5.424427,16.753438,21.302311,20.977987,42.279099
2,1005,Alabama,Barbour,25.530768,41.2,28.0,12.466974,13.710555,1005,24686,17.5,21.9,10.739667,17.673231,20.586567,19.691323,67.789635
3,1007,Alabama,Bibb,23.084813,37.4,33.4,15.420603,9.255242,1007,22394,13.6,15.1,2.601627,13.429904,20.349201,16.669644,68.352607
4,1009,Alabama,Blount,22.954959,33.0,33.3,15.833284,10.125665,1009,57826,14.6,13.6,2.880150,17.934702,22.922215,18.700930,89.951502

In [12]:
health.drop(columns = ['FIPS_x', 'FIPS_y'], inplace = True)

In [15]:
health.head()

,State,County,% Smokers,% Adults with Obesity,% Physically Inactive,% Excessive Drinking,% Severe Housing Problems,Population,% Adults with Diabetes,% Food Insecure,% Limited Access to Healthy Foods,% Uninsured,% Less Than 18 Years of Age,% 65 and Over,% Rural
0,Alabama,Autauga,19.810766,33.0,30.6,14.473886,13.630967,55869,12.7,15.6,11.991125,13.007961,23.206071,15.973080,42.002162
1,Alabama,Baldwin,18.513318,30.0,24.7,18.736958,12.996651,223234,10.3,12.9,5.424427,16.753438,21.302311,20.977987,42.279099
2,Alabama,Barbour,25.530768,41.2,28.0,12.466974,13.710555,24686,17.5,21.9,10.739667,17.673231,20.586567,19.691323,67.789635
3,Alabama,Bibb,23.084813,37.4,33.4,15.420603,9.255242,22394,13.6,15.1,2.601627,13.429904,20.349201,16.669644,68.352607
4,Alabama,Blount,22.954959,33.0,33.3,15.833284,10.125665,57826,14.6,13.6,2.880150,17.934702,22.922215,18.700930,89.951502

In [16]:
health.to_excel('../data/raw_data/2021 County Health Rankings Data - v1-copy.xlsx')